const JS = String.raw`(function(){
'use strict';
var NIGHT='https://oggwpvdirkrnzoolparx.supabase.co/functions/v1/nycif-night-layers';
var SPECIAL='https://oggwpvdirkrnzoolparx.supabase.co/functions/v1/nycif-special-calendars';
var APIKEY='sb_publishable_V5PfbUnBmRxlVVS6TtOHHQ_av0Fzo3Z';
var root=document.getElementById('nycifUnifiedApp'),chips=root&&root.querySelector('.u-chips');if(!root||!chips)return;
['nycif-time-controls-v7-style','nycif-time-controls-v8-style','nycif-time-controls-v9-style','nycif-time-controls-v10-style','nycif-time-controls-v11-style','nycif-time-controls-v12-style','nycif-time-controls-v13-style','nycif-time-controls-v14-style'].forEach(function(id){var n=document.getElementById(id);if(n)n.remove();});
var css=document.createElement('style');css.id='nycif-time-controls-v14-style';css.textContent=[
'.u-topbar{position:absolute!important;z-index:9000!important}',
'.u-chips{position:absolute!important;z-index:8990!important;top:84px!important;width:min(94vw,720px)!important;height:50px!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;padding:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}',
'.u-chip{height:48px!important;border:1px solid rgba(255,255,255,.28)!important;border-radius:999px!important;background:#09090a!important;color:#fff!important;font-size:13px!important;font-weight:650!important;padding:0 12px!important;box-shadow:none!important}',
'.u-chip .round{display:none!important}.u-chip.is-active{background:#f7f7f8!important;color:#080809!important;border-color:#f7f7f8!important;font-weight:850!important}',
'.u-special-calendars,.u-night-subfilters,.u-seven-preview{position:absolute;z-index:8985;top:143px;left:50%;transform:translateX(-50%);width:min(94vw,720px);pointer-events:auto}',
'.u-special-calendars{display:none}.u-special-calendars.on{display:grid;gap:7px}.nycif-hide-special .u-special-calendars{display:none!important}',
'.u-special-card,.u-seven-card,.u-tonight-card{background:#050506;color:#fff;border:1px solid rgba(255,255,255,.17);border-radius:18px;box-shadow:0 8px 24px rgba(0,0,0,.28);overflow:hidden}',
'.u-special-titlebar,.u-context-title{appearance:none;border:0;background:transparent;color:#fff;width:100%;height:46px;padding:0 18px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:12px;font-weight:720;letter-spacing:.22em;text-transform:uppercase;cursor:pointer;position:relative}',
'.u-special-titlebar:after,.u-context-title:after{content:"";position:absolute;left:10px;right:10px;bottom:0;height:3px;background:#ef233c;border-radius:3px}',
'.u-special-titlebar.is-active{color:#fff}.u-special-days,.u-seven-days{display:flex;align-items:stretch;gap:3px;overflow-x:auto;scrollbar-width:none;padding:8px 10px 10px}.u-special-days::-webkit-scrollbar,.u-seven-days::-webkit-scrollbar{display:none}',
'.u-special-day,.u-seven-day{appearance:none;border:0;flex:0 0 auto;min-width:61px;height:50px;border-radius:10px;background:transparent;color:#e8e8ea;display:grid;align-content:center;gap:2px;text-align:center;cursor:pointer;padding:3px 7px}',
'.u-special-day .date,.u-seven-day .date{font-size:10px;white-space:nowrap}.u-special-day .dow,.u-seven-day .dow{font-size:8px;letter-spacing:.09em;color:#aeb0b6}.u-special-day.is-active,.u-seven-day.is-active{background:#e91f37;color:#fff;box-shadow:0 0 18px rgba(233,31,55,.34)}.u-special-day.is-active .dow,.u-seven-day.is-active .dow{color:#fff}',
'.u-special-scroll,.u-seven-scroll{position:absolute;top:58px;width:26px;height:38px;border:0;background:linear-gradient(90deg,#050506 50%,transparent);color:#fff;z-index:3;font-size:24px;display:grid;place-items:center;cursor:pointer}.u-special-scroll.left,.u-seven-scroll.left{left:2px}.u-special-scroll.right,.u-seven-scroll.right{right:2px;transform:scaleX(-1)}',
'.u-night-subfilters{display:none}.u-night-subfilters.is-active{display:block}.u-tonight-card{padding-bottom:8px}.u-tonight-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;padding:8px 10px 4px}.u-night-chip{appearance:none;border:1px solid rgba(255,255,255,.18);border-radius:12px;min-height:46px;background:#101113;color:#fff;font-size:9px;font-weight:760;padding:5px 6px;cursor:pointer}.u-night-chip.is-active{background:#e91f37;border-color:#e91f37}.u-night-chip span{display:block;font-size:17px;margin-bottom:2px}',
'.u-seven-preview{display:none}.u-seven-preview.is-active{display:block}',
'.nycif-context-open .u-list{top:266px!important}.nycif-context-open .leaflet-top.leaflet-right{top:242px!important}',
'.nycif-special-active .u-night-subfilters,.nycif-special-active .u-seven-preview{display:none!important}',
'.nycif-special-active .u-special-calendars{display:grid!important}',
'.nycif-mode-tonight .u-special-calendars,.nycif-mode-seven .u-special-calendars{display:none!important}',
'.nycif-mode-now .u-night-subfilters,.nycif-mode-seven .u-night-subfilters{display:none!important}',
'.nycif-mode-now .u-seven-preview,.nycif-mode-tonight .u-seven-preview{display:none!important}',
'.nycif-night-pin-icon{background:transparent!important;border:0!important}.nycif-night-pin-shell{width:42px;height:52px;position:relative;display:grid;place-items:start center}.nycif-night-pin-face{width:35px;height:35px;border-radius:50%;background:#09090b;border:2px solid #fff;box-shadow:0 0 0 3px var(--night-tone),0 0 14px color-mix(in srgb,var(--night-tone) 70%,transparent);display:grid;place-items:center;font-size:18px}.nycif-night-pin-tail{position:absolute;top:34px;width:2px;height:12px;background:var(--night-tone)}.nycif-night-pin-dot{position:absolute;top:44px;width:7px;height:7px;border-radius:50%;background:#09090b;border:2px solid var(--night-tone)}',
'@media(max-width:782px){.u-topbar{position:absolute!important;z-index:9000!important}.u-chips{position:absolute!important;z-index:8990!important;top:78px!important;width:94vw!important;height:48px!important;gap:7px!important}.u-chip{height:46px!important;font-size:12px!important}.u-special-calendars,.u-night-subfilters,.u-seven-preview{top:134px;width:94vw}.u-special-titlebar,.u-context-title{height:43px;font-size:11px}.u-special-days,.u-seven-days{padding:7px 8px 9px}.u-special-day,.u-seven-day{min-width:58px;height:48px}.nycif-context-open .u-list{top:252px!important}.u-tonight-options{gap:5px;padding:7px 8px 4px}.u-night-chip{font-size:8.5px}}'
].join('');document.head.appendChild(css);
var oldNow=chips.querySelector('[data-mode="NOW"]'),todayChip=chips.querySelector('[data-mode="TODAY"]'),coming=chips.querySelector('[data-mode="COMING"]'),seven=chips.querySelector('[data-mode="7D"]');if(oldNow)oldNow.remove();if(coming)coming.remove();if(todayChip){todayChip.innerHTML='<span>Now</span>';todayChip.setAttribute('data-public-mode','NOW');}var tonight=chips.querySelector('[data-mode="TONIGHT"]');if(tonight)tonight.innerHTML='<span>Tonight</span>';if(seven)seven.innerHTML='<span>7 Days</span>';
var oldSub=document.querySelector('.u-night-subfilters');if(oldSub)oldSub.remove();var sub=document.createElement('div');sub.className='u-night-subfilters';sub.innerHTML='<div class="u-tonight-card"><div class="u-context-title">Tonight</div><div class="u-tonight-options"><button class="u-night-chip" type="button" data-night-layer="5pm"><span>🍹</span>It&#39;s 5 PM Somewhere</button><button class="u-night-chip" type="button" data-night-layer="dispensary"><span>🌿</span>Cannabis Shops</button><button class="u-night-chip" type="button" data-night-layer="liquor"><span>🍸</span>Liquor Stores</button></div></div>';chips.insertAdjacentElement('afterend',sub);
var oldSpecial=document.querySelector('.u-special-calendars');if(oldSpecial)oldSpecial.remove();var specialHost=document.createElement('div');specialHost.className='u-special-calendars';sub.insertAdjacentElement('beforebegin',specialHost);var sevenHost=document.createElement('div');sevenHost.className='u-seven-preview';sub.insertAdjacentElement('afterend',sevenHost);
var nightKey=null,nightCache={},nightOverlay=null,specialState=null,sevenState=null,collections=[];
function adapter(){return window.NYCIF_MAPS&&window.NYCIF_MAPS.uEventMap||null;}function map(){var a=adapter();return a&&a.map||null;}function source(){var a=adapter();return a&&(a.getSource?a.getSource('eventsSrc'):a.sources&&a.sources.eventsSrc)||null;}function group(){var a=adapter();return a&&a.layerGroups&&a.layerGroups.eventsPins;}function hideEvents(){var m=map(),g=group();if(m&&g&&m.hasLayer(g))m.removeLayer(g);}function showEvents(){var m=map(),g=group();if(m&&g&&!m.hasLayer(g))g.addTo(m);}function clearNight(){var m=map();if(m&&nightOverlay&&m.hasLayer(nightOverlay))m.removeLayer(nightOverlay);nightOverlay=null;}
function allEvents(){return root.__nycifAllEvents&&root.__nycifAllEvents.features||[];}function setSource(features){var s=source(),d={type:'FeatureCollection',features:features||[]};if(s){if(s.setData)s.setData(d);else s.data=d;}showEvents();}function fit(features){var a=adapter();if(a&&typeof a.fitFeatures==='function')a.fitFeatures(features||[]);}
function nyDate(d){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}function nyAddDays(day,offset){var p=String(day).split('-').map(Number);return nyDate(new Date(Date.UTC(p[0],p[1]-1,p[2]+offset,16,0,0)));}function nyHour(d){return Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',hour12:false}).format(d));}function eventStart(f){var p=f&&f.properties||{},v=p.start_date_time||p.start_at||p.event_date;var d=v?new Date(v):null;return d&&Number.isFinite(d.getTime())?d:null;}
function nextSevenKeys(){var today=nyDate(new Date()),out=[];for(var i=1;i<=7;i++)out.push(nyAddDays(today,i));return out;}
function sevenWindowRows(){var keys=nextSevenKeys();return allEvents().filter(function(f){var x=eventStart(f);return x&&keys.indexOf(nyDate(x))>=0;});}
function strictTonightRows(){var now=new Date();return allEvents().filter(function(f){var x=eventStart(f);return x&&nyDate(x)===nyDate(now)&&nyHour(x)>=18&&nyHour(x)<=23;});}
function nowRows(){var today=nyDate(new Date());return allEvents().filter(function(f){var x=eventStart(f);return x&&nyDate(x)===today;});}
function mapped(rows){return (rows||[]).filter(function(f){return !!f.geometry;});}
function showNow(){var rows=mapped(nowRows());setSource(rows);fit(rows);closeList();}
function strictTonight(){var rows=mapped(strictTonightRows());setSource(rows);fit(rows);}
function nightCfg(k){return k==='dispensary'?{tone:'#2f9e5b',emoji:'🌿'}:k==='liquor'?{tone:'#c47a18',emoji:'🍸'}:{tone:'#c026d3',emoji:'🍹'};}function nightIcon(k){var c=nightCfg(k);return L.divIcon({className:'nycif-night-pin-icon',html:'<div class="nycif-night-pin-shell" style="--night-tone:'+c.tone+'"><div class="nycif-night-pin-face">'+c.emoji+'</div><span class="nycif-night-pin-tail"></span><span class="nycif-night-pin-dot"></span></div>',iconSize:[42,52],iconAnchor:[21,50]});}
async function loadNight(k,b){if(nightCache[k])return nightCache[k];b.classList.add('is-loading');try{var r=await fetch(NIGHT+'?layer='+encodeURIComponent(k),{cache:'no-store'});if(!r.ok)throw new Error('Layer unavailable');return nightCache[k]=await r.json();}finally{b.classList.remove('is-loading');}}function renderNight(k,d){var m=map();if(!m||typeof L==='undefined')return;clearNight();nightOverlay=L.layerGroup().addTo(m);(d.features||[]).filter(function(f){var c=f&&f.geometry&&f.geometry.coordinates||[];return Number.isFinite(+c[0])&&Number.isFinite(+c[1]);}).slice(0,1000).forEach(function(f){var c=f.geometry.coordinates,p=f.properties||{};L.marker([+c[1],+c[0]],{icon:nightIcon(k),title:String(p.title||'Location')}).bindPopup('<strong>'+String(p.title||'Location').replace(/[<>&]/g,'')+'</strong>').addTo(nightOverlay);});}
async function activateNight(k,b){hideEvents();try{renderNight(k,await loadNight(k,b));}catch(e){console.error(e);nightKey=null;b.classList.remove('is-active');strictTonight();}}
function clearNightBtns(){Array.prototype.forEach.call(sub.querySelectorAll('.u-night-chip'),function(b){b.classList.remove('is-active');});}
function mode(){var a=chips.querySelector('.u-chip.is-active');if(!a)return'NOW';var m=a.getAttribute('data-mode');return m==='TONIGHT'?'TONIGHT':m==='7D'?'7D':'NOW';}
function activateChip(target){Array.prototype.forEach.call(chips.querySelectorAll('.u-chip'),function(c){c.classList.toggle('is-active',c===target);});}
function nowChip(){return chips.querySelector('[data-mode="TODAY"]')||chips.querySelector('[data-public-mode="NOW"]');}
function turnOffContext(){sevenState=null;nightKey=null;clearNightBtns();clearNight();activateChip(nowChip());syncContext();showNow();}
function syncContext(){var m=mode();root.classList.toggle('nycif-mode-now',m==='NOW');root.classList.toggle('nycif-mode-tonight',m==='TONIGHT');root.classList.toggle('nycif-mode-seven',m==='7D');root.classList.toggle('nycif-context-open',m!=='NOW'||specialHost.classList.contains('on'));if(m==='TONIGHT'&&!specialState){sub.classList.add('is-active');sevenHost.classList.remove('is-active');specialHost.classList.remove('on');if(!nightKey)strictTonight();}else if(m==='7D'&&!specialState){sub.classList.remove('is-active');specialHost.classList.remove('on');sevenHost.classList.add('is-active');renderSeven();if(!sevenState){var rows=mapped(sevenWindowRows());setSource(rows);fit(rows);closeList();}}else{sub.classList.remove('is-active');sevenHost.classList.remove('is-active');if(collections.length&&!root.classList.contains('nycif-hide-special'))specialHost.classList.add('on');}}
function clearSpecialButtons(){Array.prototype.forEach.call(specialHost.querySelectorAll('.u-special-titlebar,.u-special-day'),function(b){b.classList.remove('is-active');});}function closeList(){var h=document.getElementById('uHappeningList');if(h)h.classList.remove('is-active');}
function renderList(rows,title){var h=document.getElementById('uHappeningList');if(!h)return;h.innerHTML='';rows.forEach(function(f){var p=f.properties||{},b=document.createElement('button'),s=document.createElement('strong'),sm=document.createElement('small');b.className='u-list-item';s.textContent=p.title||'Event';sm.textContent=[p.day_bucket,p.start_time&&p.start_time!=='TBA'?p.start_time:null,p.location||p.venue_name||p.borough,p.access].filter(Boolean).join(' · ');b.appendChild(s);b.appendChild(sm);if(f.geometry)b.addEventListener('click',function(){var a=adapter();if(a)a.flyTo({center:f.geometry.coordinates,zoom:14});closeList();});h.appendChild(b);});h.classList.add('is-active');var st=document.getElementById('uStat');if(st)st.textContent=(title||'Events')+' · '+rows.length;}
function bucketWeekday(c,key){if(key==='MISC/TBA')return'TBD';var f=(c.features||[]).find(function(x){return (x.properties||{}).day_bucket===key;});var p=f&&f.properties||{},v=p.event_date||p.start_at||p.start_date_time;if(!v)return'';var d=new Date(v);if(!Number.isFinite(d.getTime()))return'';return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short'}).format(d).toUpperCase();}function dayLabel(key){return key==='MISC/TBA'?'TBD':String(key).replace(/^SEP\s+/i,'Sep ');}
function applySpecial(c,bucket){specialState={id:c.collection_id,bucket:bucket||'*'};sevenState=null;root.classList.add('nycif-special-active');clearNight();nightKey=null;clearNightBtns();sub.classList.remove('is-active');sevenHost.classList.remove('is-active');specialHost.classList.add('on');var rows=(c.features||[]).filter(function(f){return !bucket||(f.properties||{}).day_bucket===bucket;}),mappedRows=rows.filter(function(f){return !!f.geometry;});setSource(mappedRows);fit(mappedRows);clearSpecialButtons();var target=bucket?specialHost.querySelector('[data-special-day="'+bucket+'"]'):specialHost.querySelector('[data-special-title="'+c.collection_id+'"]');if(target)target.classList.add('is-active');if(bucket==='MISC/TBA'||!mappedRows.length){renderList(rows,c.display_name+' · TBD');}else closeList();var st=document.getElementById('uStat');if(st)st.textContent=rows.length+' '+c.display_name+' events · '+mappedRows.length+' pins · '+(bucket==='MISC/TBA'?'TBD':bucket||'ALL');}
function leaveSpecial(){if(!specialState)return;specialState=null;root.classList.remove('nycif-special-active');clearSpecialButtons();closeList();var active=chips.querySelector('.u-chip.is-active');if(active)active.click();}
function renderCollections(data){collections=data&&data.collections||[];specialHost.innerHTML='';if(!collections.length){specialHost.classList.remove('on');syncContext();return;}collections.forEach(function(c){var card=document.createElement('div'),title=document.createElement('button'),days=document.createElement('div');card.className='u-special-card';card.style.position='relative';title.type='button';title.className='u-special-titlebar';title.setAttribute('data-special-title',c.collection_id);title.textContent=c.display_name||c.short_label||'Special Collection';title.addEventListener('click',function(){if(specialState&&specialState.id===c.collection_id&&specialState.bucket==='*')leaveSpecial();else applySpecial(c,null);});days.className='u-special-days';(c.buckets||[]).forEach(function(x){var b=document.createElement('button');b.type='button';b.className='u-special-day';b.setAttribute('data-special-day',x.key);b.innerHTML='<span class="date">'+dayLabel(x.key)+'</span><span class="dow">'+bucketWeekday(c,x.key)+'</span>';b.title=x.count+' events';b.addEventListener('click',function(){applySpecial(c,x.key);});days.appendChild(b);});var left=document.createElement('button'),right=document.createElement('button');left.type=right.type='button';left.className='u-special-scroll left';right.className='u-special-scroll right';left.textContent=right.textContent='‹';left.addEventListener('click',function(){days.scrollBy({left:-220,behavior:'smooth'});});right.addEventListener('click',function(){days.scrollBy({left:220,behavior:'smooth'});});card.appendChild(title);card.appendChild(days);card.appendChild(left);card.appendChild(right);specialHost.appendChild(card);});syncContext();}
async function loadSpecial(){try{var r=await fetch(SPECIAL,{cache:'no-store',headers:{apikey:APIKEY}});if(!r.ok)throw new Error('Special calendar unavailable');renderCollections(await r.json());}catch(e){console.error(e);collections=[];specialHost.classList.remove('on');syncContext();}}
function labelDate(key){var p=String(key).split('-').map(Number);return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric'}).format(new Date(Date.UTC(p[0],p[1]-1,p[2],16,0,0)));}
function labelDow(key){var p=String(key).split('-').map(Number);return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short'}).format(new Date(Date.UTC(p[0],p[1]-1,p[2],16,0,0))).toUpperCase();}
function renderSeven(){var keys=nextSevenKeys(),card=sevenHost.querySelector('.u-seven-card');if(!card){card=document.createElement('div');card.className='u-seven-card';card.style.position='relative';card.innerHTML='<div class="u-context-title">7 Day Outlook</div><div class="u-seven-days"></div><button class="u-seven-scroll left" type="button">‹</button><button class="u-seven-scroll right" type="button">‹</button>';sevenHost.innerHTML='';sevenHost.appendChild(card);var days=card.querySelector('.u-seven-days');card.querySelector('.u-seven-scroll.left').addEventListener('click',function(){days.scrollBy({left:-220,behavior:'smooth'});});card.querySelector('.u-seven-scroll.right').addEventListener('click',function(){days.scrollBy({left:220,behavior:'smooth'});});}var host=card.querySelector('.u-seven-days');host.innerHTML='';keys.forEach(function(key){var b=document.createElement('button');b.type='button';b.className='u-seven-day'+(sevenState===key?' is-active':'');b.innerHTML='<span class="date">'+labelDate(key)+'</span><span class="dow">'+labelDow(key)+'</span>';b.addEventListener('click',function(){if(sevenState===key){sevenState=null;Array.prototype.forEach.call(host.querySelectorAll('.u-seven-day'),function(n){n.classList.remove('is-active');});var all=mapped(sevenWindowRows());setSource(all);fit(all);closeList();return;}sevenState=key;Array.prototype.forEach.call(host.querySelectorAll('.u-seven-day'),function(n){n.classList.remove('is-active');});b.classList.add('is-active');var rows=allEvents().filter(function(f){var d=eventStart(f);return d&&nyDate(d)===key;}),mappedRows=mapped(rows);setSource(mappedRows);fit(mappedRows);closeList();});host.appendChild(b);});}
chips.addEventListener('click',function(ev){var b=ev.target.closest('.u-chip');if(!b)return;var requested=b.getAttribute('data-mode');if((requested==='TONIGHT'||requested==='7D')&&b.classList.contains('is-active')){ev.preventDefault();ev.stopImmediatePropagation();turnOffContext();}},true);
Array.prototype.forEach.call(chips.querySelectorAll('.u-chip'),function(b){b.addEventListener('click',function(){if(specialState){specialState=null;root.classList.remove('nycif-special-active');clearSpecialButtons();closeList();}if(mode()!=='TONIGHT'){nightKey=null;clearNightBtns();clearNight();}if(b.getAttribute('data-mode')!=='7D')sevenState=null;setTimeout(syncContext,0);});});
Array.prototype.forEach.call(sub.querySelectorAll('.u-night-chip'),function(b){b.addEventListener('click',function(){if(mode()!=='TONIGHT'||specialState)return;var k=b.getAttribute('data-night-layer');if(nightKey===k){nightKey=null;b.classList.remove('is-active');clearNight();strictTonight();return;}clearNightBtns();nightKey=k;b.classList.add('is-active');activateNight(k,b);});});
root.addEventListener('nycif:events-ready',function(){if(mode()==='7D')renderSeven();if(mode()==='TONIGHT'&&!nightKey)strictTonight();if(mode()==='NOW')showNow();});
var m=map();if(m)m.on('moveend',function(){if(nightKey&&nightCache[nightKey]&&!specialState)renderNight(nightKey,nightCache[nightKey]);});syncContext();loadSpecial();
})();`;
Deno.serve((req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET,HEAD,OPTIONS" },
    });
  }
  if (req.method !== "GET" && req.method !== "HEAD") {
    return new Response("method_not_allowed", { status: 405 });
  }
  return new Response(req.method === "HEAD" ? null : JS, {
    status: 200,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
    },
  });
});
